version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: laravel-app
    environment:
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - internal
    depends_on:
      - database

  database:
    image: mariadb:10.11-jammy
    container_name: laravel-db
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Prague
    secrets:
      - db_root_password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal

networks:
  internal:

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  db-data:
